[package]
name = "mailer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dev-server"
path = "src/dev-server.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
askama = "0.12.0"
async-trait = { workspace = true }
css-inline = "0.8.5"
html2text = "0.5.1"
hyper = { workspace = true }
lettre = { version = "0.10.4", features = [
  "tokio1_rustls",
  "smtp-transport",
  "tokio1",
  "tokio1-rustls-tls",
  # "native-tls",
  "builder",
  # "tokio1-native-tls",
  "rustls-tls"
], default-features = false }
nanohtml2text = "0.1.4"
prex = { version = "0.1.0", path = "../prex" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
