[package]
name = "lang-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
tokio = { version = "1.27.0", features = ["full"] }
