// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPublicUser } from "../../../../db/AdminPublicUser";

export type Output = { user: AdminPublicUser };
