// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../db/Metadata";

export interface Payload {
  email: string;
  password: string;
  accountIds?: Array<string>;
  firstName: string;
  lastName: string;
  userMetadata?: Metadata;
  systemMetadata?: Metadata;
}
