// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountLimit } from "./AccountLimit.js";

export type AccountLimits = {
  stations: AccountLimit;
  listeners: AccountLimit;
  transfer: AccountLimit;
  storage: AccountLimit;
};
