// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Station } from "./db/Station.js";

export type AdminPublicStation = Station;
