/// This file is auto generated from its Rust definition, do not edit manually


export const ACCESS_TOKEN_HEADER = "x-access-token";

export const ACCESS_TOKEN_NOT_USED_AUTOREMOVE_SECS = 604800;

export const ACCOUNT_INVITATION_VALIDITY_SECS = 604800;

export const API_IP_LIMIT = 60;

export const API_IP_LIMIT_DURATION_SECS = 60;

export const AUDIO_FILE_BYTERATE = 16000;

export const AUDIO_FILE_CHUNK_SIZE = 256000;

export const DEPLOYMENT_HEALTH_CHECK_INTERVAL_SECS = 1;

export const EMAIL_VERIFICATION_CODE_LEN = 6;

export const EMAIL_VERIFICATION_VALIDITY_SECS = 3600;

export const EXTERNAL_RELAY_NO_DATA_SHUTDOWN_SECS = 10;

export const EXTERNAL_RELAY_NO_DATA_START_SHUTDOWN_SECS = 30;

export const EXTERNAL_RELAY_NO_LISTENERS_SHUTDOWN_DELAY_SECS = 60;

export const FORWARD_IP_HEADER = "x-openstream-forwarded-ip";

export const PAYMENTS_ACCESS_TOKEN_HEADER = "x-access-token";

export const PLAYLIST_NO_LISTENERS_SHUTDOWN_DELAY_SECS = 10;

export const REAL_IP_HEADER = "x-real-ip";

export const RELAY_NO_LISTENERS_SHUTDOWN_DELAY_SECS = 10;

export const STATION_PICTURES_VERSION = 3.0;

export const STREAM_BURST_LENGTH = 12;

export const STREAM_CHANNEL_CAPACITY = 16;

export const STREAM_CHUNK_SIZE = 16000;

export const STREAM_IP_CONNECTIONS_LIMIT = 8;

export const STREAM_KBITRATE = 128;

export const TOKEN_USER_RECOVERY_VALIDITY_SECS = 3600;

export const TRANSFER_SAVE_INTERVAL_MILLIS = 5000;

export const VALIDATE_ACCOUNT_NAME_MAX_LEN = 60;

export const VALIDATE_ACCOUNT_NAME_MIN_LEN = 1;

export const VALIDATE_ADMIN_FIRST_NAME_MAX_LEN = 100;

export const VALIDATE_ADMIN_LAST_NAME_MAX_LEN = 100;

export const VALIDATE_ADMIN_PASSWORD_MAX_LEN = 60;

export const VALIDATE_ADMIN_PASSWORD_MIN_LEN = 8;

export const VALIDATE_STATION_DESC_MAX_LEN = 1000;

export const VALIDATE_STATION_DESC_MIN_LEN = 1;

export const VALIDATE_STATION_EMAIL_MAX_LEN = 100;

export const VALIDATE_STATION_EXTERNAL_RELAY_URL_MAX_LEN = 200;

export const VALIDATE_STATION_FREQUENCY_MAX = 100000.0;

export const VALIDATE_STATION_FREQUENCY_MIN = 0.0;

export const VALIDATE_STATION_NAME_MAX_LEN = 60;

export const VALIDATE_STATION_NAME_MIN_LEN = 1;

export const VALIDATE_STATION_PHONE_MAX_LEN = 60;

export const VALIDATE_STATION_SLOGAN_MAX_LEN = 100;

export const VALIDATE_STATION_SLOGAN_MIN_LEN = 1;

export const VALIDATE_STATION_URLS_MAX_LEN = 150;

export const VALIDATE_STATION_WHATSAPP_MAX_LEN = 60;

export const VALIDATE_USER_EMAIL_MAX_LEN = 80;

export const VALIDATE_USER_FIRST_NAME_MAX_LEN = 100;

export const VALIDATE_USER_LAST_NAME_MAX_LEN = 100;

export const VALIDATE_USER_PASSWORD_MAX_LEN = 60;

export const VALIDATE_USER_PASSWORD_MIN_LEN = 8;

export const VALIDATE_USER_PHONE_MAX_LEN = 40;