// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Paged<T> {
  total: number;
  skip: number;
  limit: number;
  items: Array<T>;
}
