// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "./DateTime";
import type { Metadata } from "./db/Metadata";

export type PublicAdmin = {
  _id: string;
  first_name: string;
  last_name: string;
  email: string;
  created_at: DateTime;
  updated_at: DateTime;
  system_metadata: Metadata;
};
