// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPublicAccount } from "./AdminPublicAccount";
import type { UserPublicAccount } from "./UserPublicAccount";

export type PublicAccount = AdminPublicAccount | UserPublicAccount;
