// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPublicStation } from "./AdminPublicStation";
import type { UserPublicStation } from "./UserPublicStation";

export type PublicStation = AdminPublicStation | UserPublicStation;
