// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "./DateTime.js";
import type { PublicPaymentMethodKind } from "./PublicPaymentMethodKind.js";

export type PublicPaymentMethod = {
  _id: string;
  user_id: string;
  created_at: DateTime;
  updated_at: DateTime;
  deleted_at: DateTime | null;
} & PublicPaymentMethodKind;
