// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationFrequencyKind } from "./StationFrequencyKind";

export type StationFrequency = { kind: StationFrequencyKind; freq: number };
