// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountLimits } from "./AccountLimits";
import type { DateTime } from "./DateTime";
import type { Metadata } from "./db/Metadata";

export type UserPublicAccount = {
  _id: string;
  plan_id: string;
  payment_method_id: string | null;
  name: string;
  limits: AccountLimits;
  created_at: DateTime;
  updated_at: DateTime;
  user_metadata: Metadata;
};
