// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountLimits } from "./AccountLimits";
import type { DateTime } from "./DateTime";
import type { Metadata } from "./db/Metadata";

export interface UserPublicAccount {
  _id: string;
  name: string;
  ownerId: string;
  limits: AccountLimits;
  createdAt: DateTime;
  updatedAt: DateTime;
  userMetadata: Metadata;
  sourcePassword: string;
}
