// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserAgent {
  ua: string | null;
  category: string | null;
  browserType: string | null;
  vendor: string | null;
  name: string | null;
  version: string | null;
  os: string | null;
  osVersion: string | null;
}
