// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAgent = {
  ua: string | null | undefined;
  category: string | null | undefined;
  browser_type: string | null | undefined;
  vendor: string | null | undefined;
  name: string | null | undefined;
  version: string | null | undefined;
  os: string | null | undefined;
  os_version: string | null | undefined;
};
