// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../db/Metadata";
import type { PayloadLimits } from "./PayloadLimits";

export interface Payload {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  accountName: string;
  limits?: PayloadLimits;
  accountUserMetadata?: Metadata;
  accountSystemMetadata?: Metadata;
  userUserMetadata?: Metadata;
  userSystemMetadata?: Metadata;
}
