// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationQs } from "../../../../qs/PaginationQs";
import type { VisibilityQs } from "../../../../qs/VisibilityQs";

export type Query =
  & { user_id?: string; admin_id?: string }
  & PaginationQs
  & VisibilityQs;
