[package]
name = "drop-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
log = "0.4.17"
logger = { version = "0.1.0", path = "../logger" }
parking_lot = "0.12.1"
pin-project = "1.0.12"
test-util = { version = "0.1.0", path = "../test-util" }
tokio = { version = "1.21.2", features = ["full"] }

[features]
