[package]
name = "media"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mp3 = { version = "0.1.0", path = "../mp3" }
# ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
atomic_float = "0.1.0"
burst = { version = "0.1.0", path = "../burst" }
bytes = { workspace = true }
const-str = "0.5.6"
constants = { version = "0.1.0", path = "../../config/constants" }
db = { version = "0.1.0", path = "../db" }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
futures-util = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
mongodb = { workspace = true }
parking_lot = { workspace = true, features = ["send_guard", "arc_lock"] }
rand = { workspace = true }
regex_static = { workspace = true }
serde-util = { version = "0.1.0", path = "../serde-util" }
shutdown = { version = "0.1.0", path = "../shutdown" }
stream-util = { version = "0.1.0", path = "../stream-util" }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
url = { workspace = true }
