// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentsErrorKind =
  | ({ kind: "provider" } & { provider_error_type: string | null })
  | { kind: "payload" }
  | { kind: "access-token-not-present" }
  | { kind: "access-token-mismatch" }
  | { kind: "resource-not-found" }
  | { kind: "unknown" };
