// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentsErrorKind = { kind: "provider" } | { kind: "payload" } | {
  kind: "resource-not-found";
} | { kind: "unknown" };
