// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Payload = {
  first_name: string | null;
  last_name: string | null;
  phone: string | null | null;
  language: string | null | null;
};
