// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stats } from "../../../../../stream-connection-stats/Stats";

export type Output = { stats: Stats };
