[package]
name = "ffmpeg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
bytes = "1.2.1"
constants = { version = "0.1.0", path = "../../config/constants" }
log = "0.4.17"
pin-project = "1.0.12"
spsc = { version = "0.1.0", path = "../spsc" }
stream-util = { version = "0.1.0", path = "../stream-util" }
tokio = { version = "1", features = [ "full" ] }
tokio-stream = "0.1.11"
