// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicAdmin } from "../../../../PublicAdmin.js";

export type Output = PublicAdmin;
