// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPatch } from "../../../../ops/AdminPatch.js";

export type Payload = {} & AdminPatch;
