// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisibilityKind } from "./VisibilityKind.js";

export type VisibilityQs = { show?: VisibilityKind };
