[package]
name = "macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.27"
macros-build = { version = "0.1.0", path = "../macros-build" }
once_cell = "1.18.0"
parking_lot = "0.12.1"
paste = "1.0.12"
serde = "1.0.164"
serde_json = "1.0.96"
static_init = "1.0.3"
