[package]
name = "macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { workspace = true }
macros-build = { version = "0.1.0", path = "../macros-build" }
once_cell = { workspace = true }
parking_lot = { workspace = true }
paste = "1.0.12"
serde = { workspace = true }
serde_json = { workspace = true }
static_init = { workspace = true }
