[package]
name = "openapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.16"
serde = "1.0.195"
serde_json = "1.0.111"
thiserror = "1.0.56"
ts-rs = "6.2.0"
