[package]
name = "http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.23"
merge-streams = "0.1.2"
pin-project = "1.0.12"
prex = { version = "0.1.0", path = "../prex" }
serde = "1.0.149"
serde_json = { version = "1.0", features = ["preserve_order"] }
test-util = { version = "0.1.0", path = "../test-util" }
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = "0.1.11"
