[workspace]
members = [
    "bin/openstream",
    "bin/producer",
    "bin/client",
    "bin/mixed",
    "bin/ffstress",
    "bin/hls-logger",

    "config/constants",

    "packages/ip",
    "packages/config",
    "packages/stream",
    "packages/source-alt",
    "packages/stream",
    "packages/router",
    "packages/upload",
    "packages/api",

    "packages/channels",
    "packages/db",

    "packages/validate",
    "packages/user-agent",
    "packages/spsc",
    "packages/shutdown",
    "packages/drop-tracer",
    "packages/owo-colors",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
    "packages/logger",
]

[patch.crates-io]
bson = { path = "./patches/bson" }
