[workspace]
members = [
    "bin/openstream",
    "bin/producer",
    "bin/client",
    "bin/mixed",

    "config/constants",

    "packages/config",
    "packages/stream",
    "packages/source-alt",
    "packages/stream",
    "packages/upload",
    "packages/api",

    "packages/channels",
    "packages/db",

    "packages/shutdown",
    "packages/cond-count",
    "packages/owo",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
    "packages/logger",
]