[workspace]
members = [
    "bin/bin",
    "bin/producer",

    "packages/source",
    "packages/stream",

    "packages/db",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
]