[workspace]
members = [
    "bin",
    "source-client",
    "packages/source",
    "packages/sender",
    "packages/db",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
]