[workspace]
members = [
    "bin/openstream",
    
    "internal-scripts/producer",
    "internal-scripts/client",
    "internal-scripts/mixed",
    "internal-scripts/ffstress",
    "internal-scripts/hls-logger",

    "config/constants",

    "packages/ip",
    "packages/config",
    "packages/stream",
    "packages/source-alt",
    "packages/stream",
    "packages/router",
    "packages/upload",
    "packages/api",

    "packages/http",

    "packages/channels",
    "packages/db",

    "packages/validate",
    "packages/user-agent",
    "packages/spsc",
    "packages/shutdown",
    "packages/drop-tracer",
    "packages/owo-colors",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
    "packages/logger",
    "packages/env_logger",
]

[patch.crates-io]
bson = { path = "./patches/bson" }
ts-rs = { path = "./patches/ts-rs/ts-rs" }
