[workspace]
members = [
    "bin/bin",
    "bin/producer",

    "config/constants",

    "packages/stream",
    "packages/source-alt",
    "packages/stream",
    "packages/upload",
    "packages/api",

    "packages/channels",
    "packages/db",

    "packages/owo",
    "packages/prex",
    "packages/uid",
    "packages/crypt",
    "packages/ffmpeg",
    "packages/serde-util",
    "packages/stream-util",
    "packages/logger",
]