# access related settings
[access]
# string[] (required)
# each global access token must have 10 characters or more 
global_access_tokens = []

# mongodb related settings
[mongodb]

# string (required)
# must have a defined database in the path and a replicaSet in the query params
# internally openstream uses transactions so replicaSet is required
url="mongodb://localhost:27017/openstream?replicaSet=rs1"



# the [stream] server is where end users will connect to listen to the streams
[stream]

# string(SocketAddr)[] (required)
# socket addrs to bind the stream server to
addrs = [ "0.0.0.0:20200" ]

# string (required)
# public url to access the stream server
public_base_url = "http://stream.openstream.fm"



# the [source receiver] is the icecast compatible server where streamers will connect to start live broadcasting
[source.receiver]

# string(SocketAddr)[] (required)
# socket addrs to bind the source receiver server to
addrs = [ "0.0.0.0:20600" ]

# string (required)
# public url to access the source receiver server
public_base_url = "http://source.openstream.fm"



# the [source broadcaster] server is where stream servers connect with source servers
[source.broadcaster]

# string(SocketAddr)[] (required)
# socket addrs to bind the source broadcaster server to
addrs = [ "0.0.0.0:20300", "0.0.0.0:20301", "0.0.0.0:20302", "0.0.0.0:20303", "0.0.0.0:20304" ]

# string (required)
# public url to access the source broadcaster server
public_base_url = "http://broad.openstream.fm"



# the [api] server is the main interface for users and admins to interact with openstream server
[api]

# string(SocketAddr)[] (required)
# socket addrs to bind the api server to
addrs = [ "0.0.0.0:20700" ]

# string (required)
# public url to access the source api server
public_base_url = "http://api.openstream.fm"

