// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StatsItem {
  sessions: number;
  ips: number;
  country_sessions: Record<string, number | undefined>;
  country_ips: Record<string, number | undefined>;
}
