// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsItem } from "./StatsItem";

export interface Stats {
  total: number;
  sample: number;
  multiplier: number;
  sampled: boolean;
  now: StatsItem;
  last_24h: StatsItem;
  last_7d: StatsItem;
  last_30d: StatsItem;
}
