// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsItem } from "./StatsItem";

export interface Stats {
  time_now: StatsItem;
  time_24h: StatsItem;
  time_7d: StatsItem;
  time_30d: StatsItem;
}
