[package]
name = "mp3"
version = "0.3.4"
# authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "Metadata parser for MP3 files"
repository = "https://github.com/GuillaumeGomez/mp3-metadata"
license = "MIT"

keywords = ["mp3", "metadata"]

[lib]
name = "mp3"

[dev-dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
simplemad = "0.9"
