[package]
name = "user-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prex = { version = "0.1.0", path = "../prex" }
serde = { version = "1.0.147", features = ["derive"] }
static_init = "1.0.3"
woothee = "0.13.0"
