[package]
name = "constants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { version = "0.1.0", path = "../../packages/macros" }
static_init = "1.0.3"
