[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
db = { version = "0.1.0", path = "../db" }
futures = { workspace = true }
http = { version = "0.1.0", path = "../http" }
hyper = { workspace = true }
log = { workspace = true }
mongodb = { workspace = true }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
prex = { version = "0.1.0", path = "../prex" }
serde = { workspace = true }
shutdown = { version = "0.1.0", path = "../shutdown" }
socket2 = "0.4.7"
thiserror = { workspace = true }
tokio = { workspace = true }
