[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
db = { version = "0.1.0", path = "../db" }
futures = "0.3.25"
http = { version = "0.1.0", path = "../http" }
hyper = { version = "0.14.27", features = ["full"] }
log = "0.4.17"
mongodb = "2.7.0"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
prex = { version = "0.1.0", path = "../prex" }
serde = { version = "1.0.147", features = ["derive"] }
shutdown = { version = "0.1.0", path = "../shutdown" }
socket2 = "0.4.7"
thiserror = "1.0.38"
tokio = { version = "1.29.0", features = ["full"] }
