[package]
name = "drop-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# futures = { workspace = true }
# pin-project = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
logger = { version = "0.1.0", path = "../logger" }

[features]
