[package]
name = "drop-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# futures = "0.3.25"
# pin-project = "1.0.12"
log = "0.4.17"
parking_lot = "0.12.1"
tokio = { version = "1.27.0", features = ["full"] }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
logger = { version = "0.1.0", path = "../logger" }

[features]
