[package]
name = "stream-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
pin-project = "1.0.12"
test-util = { version = "0.1.0", path = "../test-util" }
tokio = { version = "1", features = [ "full" ] }
tokio-stream = "0.1.10"
tokio-test = "0.4.2"

[dev-dependencies]
async-stream = "0.3.3"
