[package]
name = "stream-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
pin-project = "1.0.12"
tokio = { version = "1.27.0", features = [ "full" ] }
tokio-stream = "0.1.10"

[dev-dependencies]
# tokio-test = "0.4.2"
async-stream = "0.3.3"
test-util = { version = "0.1.0", path = "../test-util" }
