[package]
name = "stream-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
pin-project = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
# tokio-test = "0.4.2"
async-stream = { workspace = true }
test-util = { version = "0.1.0", path = "../test-util" }
