[package]
name = "source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
channels = { version = "0.1.0", path = "../channels" }
constants = { version = "0.1.0", path = "../../config/constants" }
ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
hyper = "0.14.20"
log = "0.4.17"
owo = { version = "3.5.0", path = "../owo" }
prex = { version = "0.1.0", path = "../prex" }
stream-util = { version = "0.1.0", path = "../stream-util" }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.10"

[features]
