[package]
name = "serde-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
hyper = { workspace = true }
iso8601-timestamp = "0.2.7"
log = { workspace = true }
mongodb = { workspace = true }
openapi = { version = "0.1.0", path = "../openapi" }
schemars = { workspace = true, features = ["preserve_order", "chrono"] }
serde = { workspace = true }
serde_json = { workspace = true }
static_init = { workspace = true }
time = { workspace = true, features = ["serde-well-known", "local-offset", "serde-human-readable", "macros"] }
ts-rs = { workspace = true }
