[package]
name = "serde-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bytes = "1.2.1"
chrono = { version = "0.4", features = ["serde"] }
hyper = "0.14.27"
iso8601-timestamp = "0.2.7"
log = "0.4.17"
mongodb = "2.7.0"
schemars = { version = "0.8.16", features = ["preserve_order", "chrono"] }
serde = "1"
serde_json = { version = "1.0", features = ["preserve_order"] }
static_init = "1.0.3"
time = { version = "0.3.17", features = ["serde-well-known", "local-offset", "serde-human-readable", "macros"] }
ts-rs = "6.2.0"
