[package]
name = "http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { version = "0.1.0", path = "../db" }
# merge-streams = "0.1.2"
# tokio-stream = { workspace = true }
hyper = { workspace = true }
mongodb = { workspace = true }
pin-project = { workspace = true }
prex = { version = "0.1.0", path = "../prex" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
