// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAgent } from "../UserAgent";

export type AccessTokenGeneratedBy =
  | { generatedBy: "login"; ip: string; user_agent: UserAgent }
  | { generatedBy: "register"; ip: string; user_agent: UserAgent }
  | { generatedBy: "api"; title: string }
  | { generatedBy: "cli"; title: string };
