// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccessTokenScope = { scope: "global" } | {
  scope: "admin";
  admin_id: string;
} | { scope: "user"; user_id: string };
