// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAgent } from "../UserAgent";

export type AccessTokenGeneratedBy =
  | ({ generated_by: "login" } & {
    ip: string;
    user_agent: UserAgent;
    device_id: string;
  })
  | ({ generated_by: "register" } & {
    ip: string;
    user_agent: UserAgent;
    device_id: string;
  })
  | ({ generated_by: "api" } & { title: string })
  | ({ generated_by: "cli" } & { title: string });
