// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export type AccountInvitationState =
  | { state: "pending" }
  | ({ state: "accepted" } & { used_at: DateTime })
  | ({ state: "rejected" } & { used_at: DateTime });
