// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountLimits } from "../AccountLimits";
import type { DateTime } from "../DateTime";
import type { Metadata } from "./Metadata";

export type Account = {
  _id: string;
  plan_id: string;
  payment_method_id: string | null;
  name: string;
  limits: AccountLimits;
  user_metadata: Metadata;
  system_metadata: Metadata;
  created_at: DateTime;
  updated_at: DateTime;
  deleted_at: DateTime | null;
};
