// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export interface AudioChunk {
  _id: string;
  audioFileId: string;
  accountId: string;
  startMs: number;
  endMs: number;
  i: number;
  len: number;
  durationMs: number;
  bytesSec: number;
  data: string;
  createdAt: DateTime;
}
