// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioMetadata } from "./AudioMetadata";

export interface AudioFile {
  _id: string;
  accountId: string;
  md5: string;
  len: number;
  durationMs: number;
  bytesSec: number;
  chunkCount: number;
  chunkLen: number;
  chunkDurationMs: number;
  createdAt: string;
  filename: string;
  metadata: AudioMetadata;
}
