// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export type AudioChunk = {
  _id: string;
  audio_file_id: string;
  station_id: string;
  start_ms: number;
  end_ms: number;
  i: number;
  len: number;
  duration_ms: number;
  bytes_sec: number;
  data: string;
  created_at: DateTime;
};
