// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioUploadOperationState } from "./AudioUploadOperationState.js";
import type { DateTime } from "../DateTime.js";

export type AudioUploadOperation = {
  _id: string;
  station_id: string;
  deployment_id: string;
  created_at: DateTime;
} & AudioUploadOperationState;
