// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export interface BaseAudioUploadOperation {
  _id: string;
  account_id: string;
  created_at: DateTime;
}
