// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { UserAgent } from "../UserAgent";

export interface BaseConnection {
  accountId: string;
  ip: string;
  userAgent: UserAgent;
  requestHeaders: { [key: string]: string };
  connectedAt: DateTime;
  transferBytes: number;
}
