// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export interface BasePlayHistoryItem {
  _id: string;
  station_id: string;
  name: string;
  artist: string | null;
  created_at: DateTime;
}
