// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessTokenGeneratedBy } from "./AccessTokenGeneratedBy.js";
import type { AccessTokenScope } from "./AccessTokenScope.js";
import type { DateTime } from "../DateTime.js";

export type BaseAccessToken =
  & {
    _id: string;
    hash: string;
    media_hash: string;
    last_used_at: DateTime | null | undefined;
    hits: number;
    created_at: DateTime;
    deleted_at: DateTime | null | undefined;
  }
  & AccessTokenScope
  & AccessTokenGeneratedBy;
