// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export interface BaseAccessToken {
  _id: string;
  key: string;
  created_at: DateTime;
  last_used_at: DateTime | null;
  hits: number;
}
