// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { EventVariant } from "./EventVariant";

export type BaseEvent = { _id: string; created_at: DateTime } & EventVariant;
