// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessTokenGeneratedBy } from "./AccessTokenGeneratedBy";
import type { AccessTokenScope } from "./AccessTokenScope";
import type { DateTime } from "../DateTime";

export type BaseAccessToken =
  & {
    _id: string;
    hash: string;
    media_hash: string;
    last_used_at: DateTime | null;
    hits: number;
    created_at: DateTime;
    deleted_at: DateTime | null;
  }
  & AccessTokenScope
  & AccessTokenGeneratedBy;
