// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLimits } from "./ConfigLimits.js";

export type Config = { _id: string; limits: ConfigLimits };
