// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { DeploymentState } from "./DeploymentState";

export interface Deployment {
  _id: string;
  local_ip: string;
  pid: number;
  source_ports: Array<number>;
  stream_ports: Array<number>;
  api_ports: Array<number>;
  state: DeploymentState;
  created_at: DateTime;
  updated_at: DateTime;
  dropped_at: DateTime | null;
}
