// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";
import type { DeploymentState } from "./DeploymentState.js";

export type Deployment = {
  _id: string;
  local_ip: string;
  pid: number;
  source_ports: Array<number>;
  stream_ports: Array<number>;
  api_ports: Array<number>;
  state: DeploymentState;
  created_at: DateTime;
  updated_at: DateTime;
  health_checked_at: DateTime | null | undefined;
  dropped_at: DateTime | null | undefined;
  _m: boolean;
};
