// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value.js";

export type Document = { [key: string]: Value };
