// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioListenerEnd } from "./event-payload/AudioListenerEnd.js";
import type { AudioListenerStart } from "./event-payload/AudioListenerStart.js";

export type EventVariant = {
  kind: "listener.start";
  payload: AudioListenerStart;
} | { kind: "listener.end"; payload: AudioListenerEnd };
