// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";
import type { MediaSessionKind } from "./MediaSessionKind.js";
import type { MediaSessionNowPlaying } from "./MediaSessionNowPlaying.js";
import type { MediaSessionState } from "./MediaSessionState.js";

export type MediaSession = {
  _id: string;
  station_id: string;
  deployment_id: string;
  state: MediaSessionState;
  now_playing: MediaSessionNowPlaying | null | undefined;
  transfer_bytes: number;
  closed_at: DateTime | null | undefined;
  duration_ms: number | null | undefined;
  health_checked_at: DateTime | null | undefined;
  created_at: DateTime;
  updated_at: DateTime;
} & MediaSessionKind;
