// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { MediaSessionKind } from "./MediaSessionKind";
import type { MediaSessionNowPlaying } from "./MediaSessionNowPlaying";
import type { MediaSessionState } from "./MediaSessionState";

export type MediaSession = {
  _id: string;
  station_id: string;
  deployment_id: string;
  state: MediaSessionState;
  now_playing: MediaSessionNowPlaying | null;
  transfer_bytes: number;
  closed_at: DateTime | null;
  duration_ms: number | null;
  health_checked_at: DateTime | null;
  created_at: DateTime;
  updated_at: DateTime;
} & MediaSessionKind;
