// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";
import type { Request } from "./http/Request.js";

export type MediaSessionKind =
  | ({ kind: "playlist" } & {
    resumed_from: string | null | undefined;
    last_audio_file_id: string;
    last_audio_file_order: number;
    last_audio_chunk_i: number;
    last_audio_chunk_skip_parts: number;
    last_audio_chunk_date: DateTime;
  })
  | ({ kind: "live" } & { request: Request })
  | ({ kind: "external-relay" } & { url: string });
