// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";

export type OwnerDeploymentInfo = {
  deployment_id: string;
  task_id: string;
  content_type: string;
  health_checked_at: DateTime | null;
};
