// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { PlayHistoryItemKind } from "./PlayHistoryItemKind";

export type PlayHistoryItem = {
  _id: string;
  station_id: string;
  deployment_id: string;
  title: string;
  artist: string | null;
  created_at: DateTime;
} & PlayHistoryItemKind;
