// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayHistoryItemKind = { kind: "live" } | {
  kind: "playlist";
  playlist_id: string;
  file_id: string;
};
