// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProbeResult =
  | ({ r: "ok" } & { document: Record<string, any> })
  | ({ r: "error" } & {
    error_exit_code: number | null | undefined;
    error_stdout: string | null | undefined;
    error_stderr: string | null | undefined;
    error_display: string;
    error_debug: string;
  });
