// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPublicUser } from "./AdminPublicUser.js";
import type { UserPublicUser } from "./UserPublicUser.js";

export type PublicUser = AdminPublicUser | UserPublicUser;
