// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SentEmailKind = {
  kind: "user-recovery";
  data: { user_id: string; token_id: string };
} | {
  kind: "email-verification-code";
  data: { email: string; code_id: string };
} | {
  kind: "account-invitation";
  data: {
    receiver_email: string;
    invitation_id: string;
    user_sender_id: string | null | undefined;
    admin_sender_id: string | null | undefined;
  };
};
