// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SentEmailKind = {
  kind: "user-recovery";
  data: { user_id: string; token_id: string };
};
