// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export type StationFilesPreShuffleCheckpoint = {
  _id: string;
  file_ids: Array<string>;
  created_at: DateTime;
};
