// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";

export type StationSlug = {
  _id: string;
  station_id: string;
  slug: string;
  created_at: DateTime;
};
