// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";

export interface StationPicture {
  _id: string;
  version: number;
  src_filename: string;
  src_content_type: string;
  src_size: number;
  src_size_bytes: number;
  created_at: DateTime;
  updated_at: DateTime;
}
