// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { Metadata } from "./Metadata";
import type { StationFrequency } from "../StationFrequency";
import type { StationLimits } from "../StationLimits";

export interface Station {
  _id: string;
  account_id: string;
  name: string;
  slug: string;
  slogan: string | null;
  description: string | null;
  frequencies: Array<StationFrequency>;
  email: string | null;
  whatsapp: string | null;
  website_url: string | null;
  twitter_url: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  youtube_url: string | null;
  twitch_url: string | null;
  google_play_url: string | null;
  app_store_url: string | null;
  user_metadata: Metadata;
  system_metadata: Metadata;
  limits: StationLimits;
  playlist_is_randomly_shuffled: boolean;
  source_password: string;
  created_at: DateTime;
  updated_at: DateTime;
  deleted_at: DateTime | null;
}
