// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../CountryCode.js";
import type { DateTime } from "../DateTime.js";

export type StreamConnectionLite = {
  _id: string;
  st: string;
  op: boolean;
  ip: string;
  cc: CountryCode | null | undefined;
  du: number | null | undefined;
  by: number | null | undefined;
  br: string | null | undefined;
  do: string | null | undefined;
  os: string | null | undefined;
  ca: DateTime;
  re: boolean;
  _m: boolean;
  cl: DateTime | null | undefined;
};
