// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../CountryCode";
import type { DateTime } from "../DateTime";
import type { Request } from "./http/Request";

export interface StreamConnection {
  _id: string;
  station_id: string;
  transfer_bytes: number;
  duration_ms: number | null;
  is_open: boolean;
  created_at: DateTime;
  country_code: CountryCode | null;
  ip: string;
  request: Request;
  last_transfer_at: DateTime;
}
