// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";

export type TokenUserRecovery = {
  _id: string;
  hash: string;
  user_id: string;
  used_at: DateTime | null | undefined;
  created_at: DateTime;
};
