// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";

export type TransferCheckpoint = {
  _id: string;
  year: number;
  month: number;
  matched_count: number;
  modified_count: number;
  created_at: DateTime;
};
