// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { Metadata } from "./Metadata";

export interface UserPublicUser {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
  createdAt: DateTime;
  updatedAt: DateTime;
  userMetadata: Metadata;
}
