// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime";
import type { Metadata } from "./Metadata";

export interface UserPublicUser {
  _id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  language: string | null;
  created_at: DateTime;
  updated_at: DateTime;
  user_metadata: Metadata;
}
