// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../CountryCode.js";
import type { DateTime } from "../DateTime.js";

export type WsStatsConnection = {
  _id: string;
  st: string;
  dp: string;
  du: number | null;
  op: boolean;
  cc: CountryCode | null;
  ip: string;
  ap: string | null;
  av: number | null;
  re: number;
  ca: DateTime;
  cl: DateTime | null;
};
