// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicUser } from "../../../db/PublicUser";

export type Output = { user: PublicUser };
