[package]
name = "openstream"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
source = { path = "../../packages/source" }
source-alt = { path = "../../packages/source-alt" }
stream = { path = "../../packages/stream" }
logger = { path = "../../packages/logger" }
log = "0.4.17"
dotenv = "0.15.0"
channels = { version = "0.1.0", path = "../../packages/channels" }
owo-colors = { version = "3.5.0", path = "../../packages/owo-colors" }
config = { version = "0.1.0", path = "../../packages/config" }
db = { version = "0.1.0", path = "../../packages/db" }
mongodb = { version = "=2.3.1", features = [ "zstd-compression" ] }
rust_ipify = "1.1.0"
drop-tracer = { version = "0.1.0", path = "../../packages/drop-tracer" }
shutdown = { version = "0.1.0", path = "../../packages/shutdown" }
ip = { version = "0.1.0", path = "../../packages/ip" }
which = "4.3.0"
clap = { version = "4.0.26", features = ["derive"] }
futures = "0.3.25"
api = { version = "0.1.0", path = "../../packages/api" }
chrono = "0.4.23"
dialoguer = "0.10.2"
router = { version = "0.1.0", path = "../../packages/router" }
defer-lite = "1.0.0"
anyhow = "1.0.66"
serde-util = { version = "0.1.0", path = "../../packages/serde-util" }
media-sessions = { version = "0.1.0", path = "../../packages/media-sessions" }
jemallocator = "0.5.0"
uid = { version = "0.1.0", path = "../../packages/uid" }
local-ip-address = "0.5.0"
