[package]
name = "openstream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
source = { path = "../../packages/source" }
source-alt = { path = "../../packages/source-alt" }
stream = { path = "../../packages/stream" }
logger = { path = "../../packages/logger" }
log = "0.4.17"
dotenv = "0.15.0"
channels = { version = "0.1.0", path = "../../packages/channels" }
owo = { version = "3.5.0", path = "../../packages/owo" }
config = { version = "0.1.0", path = "../../packages/config" }
db = { version = "0.1.0", path = "../../packages/db" }
mongodb = "2.3.1"
rust_ipify = "1.1.0"
cond-count = { version = "0.1.0", path = "../../packages/cond-count" }
shutdown = { version = "0.1.0", path = "../../packages/shutdown" }

[features]
# proctitle = "0.1.1"
# libuv = "2.5.0"
