// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicStation } from "../../../../../PublicStation";
import type { PublicUser } from "../../../../../db/PublicUser";

export interface Output {
  station: PublicStation;
  user: PublicUser;
  token: string;
}
