// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicAccount } from "../../../../../PublicAccount";
import type { PublicUser } from "../../../../../db/PublicUser";

export interface Output {
  user: PublicUser;
  account: PublicAccount;
  token: string;
  media_key: string;
}
