// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../../../db/Metadata";

export type Payload = {
  plan_id: string;
  email: string;
  password: string;
  phone: string | null;
  language?: string;
  first_name: string;
  last_name: string;
  account_name: string;
  user_user_metadata?: Metadata;
  user_system_metadata?: Metadata;
  account_user_metadata?: Metadata;
  account_system_metadata?: Metadata;
  email_verification_code: string;
  device_id: string;
  payment_method_nonce: string;
  payment_device_data: string | null;
};
