// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../../../db/Metadata";
import type { PayloadLimits } from "./PayloadLimits";

export interface Payload {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  station_name: string;
  limits?: PayloadLimits;
  station_user_metadata?: Metadata;
  station_system_metadata?: Metadata;
  user_user_metadata?: Metadata;
  user_system_metadata?: Metadata;
}
