[package]
name = "api2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { version = "0.1.0", path = "../../config/constants" }
crypt = { version = "0.1.0", path = "../crypt" }
db = { version = "0.1.0", path = "../db" }
derive_more = "0.99.17"
geoip = { version = "0.1.0", path = "../geoip" }
http = { version = "0.2" }
macros = { version = "0.1.0", path = "../macros" }
mongodb = "2.4.0"
serde = { version = "1.0.171", features = ["derive"] }
serde-util = { version = "0.1.0", path = "../serde-util" }
thiserror = "1.0.43"
user-agent = { version = "0.1.0", path = "../user-agent" }
