// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paged } from "../../../Paged.js";
import type { PublicInvitation } from "../../PublicInvitation.js";

export type Output = Paged<PublicInvitation>;
