// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationQs } from "../../../qs/PaginationQs";
import type { VisibilityQs } from "../../../qs/VisibilityQs";

export type Query =
  & {
    user_sender_id?: string;
    admin_sender_id?: string;
    receiver_email?: string;
    account_id?: string;
  }
  & PaginationQs
  & VisibilityQs;
