// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Query = {
  skip?: number;
  limit?: number;
  user_sender_id?: string;
  admin_sender_id?: string;
  receiver_email?: string;
  account_id?: string;
};
