// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnauthenticatedAcceptPayloadData } from "./UnauthenticatedAcceptPayloadData.js";

export type Payload = {} & UnauthenticatedAcceptPayloadData | {
  invitation_id: string;
};
