[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
constants = { version = "0.1.0", path = "../../config/constants" }
heapless = "0.7.16"
parking_lot = "0.12.1"
static_init = "1.0.3"
tokio = { version = "1.21.2", features = ["full"] }
