[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# url = { version = "2.3.1", features = ["serde"] }
json_comments = "0.2.1"
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0.38"
toml = { version = "0.5.9", features = ["indexmap", "preserve_order"] }
