[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_comments = "0.2.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { version = "0.5.9", features = ["indexmap", "preserve_order"] }

metre = { version = "0.1.0", path = "../metre" }
garde = "0.13.0"
