[package]
name = "source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
# mp3 = { version = "0.1.0", path = "../mp3" }
# channels = { version = "0.1.0", path = "../channels" }
async-trait = { workspace = true }
bytes = { workspace = true }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
constants = { version = "0.1.0", path = "../../config/constants" }
futures = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
prex = { version = "0.1.0", path = "../prex" }
shutdown = { version = "0.1.0", path = "../shutdown" }
stream-util = { version = "0.1.0", path = "../stream-util" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
http = { version = "0.1.0", path = "../http" }
db = { version = "0.1.0", path = "../db" }
thiserror = { workspace = true }
socket2 = "0.4.7"
serde-util = { version = "0.1.0", path = "../serde-util" }
geoip = { version = "0.1.0", path = "../geoip" }

[features]
