[package]
name = "source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
# mp3 = { version = "0.1.0", path = "../mp3" }
# channels = { version = "0.1.0", path = "../channels" }
async-trait = "0.1.58"
bytes = "1.2.1"
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
constants = { version = "0.1.0", path = "../../config/constants" }
futures = "0.3.25"
hyper = "0.14.27"
log = "0.4.17"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
prex = { version = "0.1.0", path = "../prex" }
shutdown = { version = "0.1.0", path = "../shutdown" }
stream-util = { version = "0.1.0", path = "../stream-util" }
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = "0.1.10"
http = { version = "0.1.0", path = "../http" }
db = { version = "0.1.0", path = "../db" }
thiserror = "1.0.38"
socket2 = "0.4.7"
media-sessions = { version = "0.1.0", path = "../media-sessions" }
serde-util = { version = "0.1.0", path = "../serde-util" }
geoip = { version = "0.1.0", path = "../geoip" }

[features]
