// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../db/Metadata";

export type Payload = {
  name: string;
  plan_id: string;
  user_id?: string;
  user_metadata?: Metadata;
  system_metadata?: Metadata;
};
