[package]
name = "stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# channels = { path = "../channels" }
bytes = { workspace = true }
hyper = { workspace = true }
prex = { version = "0.1.0", path = "../prex" }
tokio = { workspace = true }
log = { workspace = true }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
async-trait = { workspace = true }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
shutdown = { version = "0.1.0", path = "../shutdown" }
serde_json = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
http = { version = "0.1.0", path = "../http" }
db = { version = "0.1.0", path = "../db" }
serde-util = { version = "0.1.0", path = "../serde-util" }
mongodb = { workspace = true }
parking_lot = { workspace = true }
constants = { version = "0.1.0", path = "../../config/constants" }
thiserror = { workspace = true }
socket2 = "0.4.7"
ip-counter = { version = "0.1.0", path = "../ip-counter" }
ip_rfc = "0.1.0"
defer = "0.1.0"
url = { workspace = true }
rand = { workspace = true }
media = { version = "0.1.0", path = "../media" }
mp3 = { version = "0.3.4", path = "../mp3" }

[features]

