[package]
name = "media-sessions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mp3 = { version = "0.1.0", path = "../mp3" }
# ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
atomic_float = "0.1.0"
burst = { version = "0.1.0", path = "../burst" }
bytes = "1.3.0"
constants = { version = "0.1.0", path = "../../config/constants" }
db = { version = "0.1.0", path = "../db" }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
futures-util = "0.3.25"
hyper = { version = "0.14.27", features = ["full"] }
log = "0.4.17"
mongodb = "2.4.0"
parking_lot = "0.12.1"
regex_static = "0.1.1"
serde-util = { version = "0.1.0", path = "../serde-util" }
shutdown = { version = "0.1.0", path = "../shutdown" }
stream-util = { version = "0.1.0", path = "../stream-util" }
thiserror = "1.0.38"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = "0.1.11"
url = "2.4.0"
