// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PayloadLimits {
  listeners?: number;
  transfer?: number;
  storage?: number;
}
