[package]
name = "user-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepsize = { workspace = true }
prex = { version = "0.1.0", path = "../prex" }
schemars = { workspace = true, features = ["preserve_order"] }
serde = { workspace = true }
static_init = { workspace = true }
ts-rs = { workspace = true }
woothee = "0.13.0"
