[package]
name = "user-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepsize = "0.2.0"
prex = { version = "0.1.0", path = "../prex" }
schemars = { version = "0.8.16", features = ["preserve_order"] }
serde = { version = "1.0.147", features = ["derive"] }
static_init = "1.0.3"
ts-rs = "6.2.0"
woothee = "0.13.0"
