[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
chrono = "0.4.23"
config = { version = "0.1.0", path = "../config" }
crypt = { version = "0.1.0", path = "../crypt" }
db = { version = "0.1.0", path = "../db" }
futures = "0.3.25"
futures-util = "0.3.25"
hyper = { version = "0.14.20", features = ["full"] }
log = "0.4.17"
mongodb = "2.3.1"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
parking_lot = "0.12.1"
prex = { version = "0.1.0", path = "../prex" }
serde = "1.0.145"
serde-querystring = "0.0.8"
serde_json = "1.0.86"
shutdown = { version = "0.1.0", path = "../shutdown" }
static_init = "1.0.3"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
user-agent = { version = "0.1.0", path = "../user-agent" }
