[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
async-trait = "0.1.57"
bytes = "1.3.0"
chrono = "0.4.23"
config = { version = "0.1.0", path = "../config" }
constants = { version = "0.1.0", path = "../../config/constants" }
cookie = { version = "0.16.2", features = ["sha2", "secure", "signed", "base64"] }
crypt = { version = "0.1.0", path = "../crypt" }
db = { version = "0.1.0", path = "../db" }
futures = "0.3.25"
futures-util = "0.3.25"
hex = "0.4.3"
http = { version = "0.1.0", path = "../http" }
http-range = "0.1.5"
hyper = { version = "0.14.20", features = ["full"] }
log = "0.4.17"
mongodb = "=2.3.1"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
parking_lot = "0.12.1"
prex = { version = "0.1.0", path = "../prex" }
serde = "1.0.145"
serde-querystring = "0.1.0"
serde-util = { version = "0.1.0", path = "../serde-util" }
serde_json = "1.0.86"
sha1 = "0.10.5"
shutdown = { version = "0.1.0", path = "../shutdown" }
socket2 = "0.4.7"
static_init = "1.0.3"
test-util = { version = "0.1.0", path = "../test-util" }
thiserror = "1.0.38"
time = "0.3.17"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
ts-rs = { version = "6.2.0", features = ["chrono", "chrono-impl", "format"] }
upload = { version = "0.1.0", path = "../upload" }
user-agent = { version = "0.1.0", path = "../user-agent" }
validate = { version = "0.1.0", path = "../validate" }
