// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Query = {
  connection_id?: string;
  station_id: string;
  app_kind?: string;
  app_version?: number;
};
