[package]
authors = [
  "Vincent Prouillet <hello@vincentprouillet.com",
  "biblius <crazycompanyxxl@gmail.com>",
]
description = "Provides struct validation and modification functionality through the use of derive macros"
edition = "2021"
exclude = ["derive_tests/"]
homepage = "https://github.com/biblius/modify"
keywords = ["modify", "payload", "validate", "modify"]
license = "MIT"
name = "modify"
readme = "../README.md"
repository = "https://github.com/biblius/modify"
version = "1.3.0"


[dependencies]
card-validate = { version = "2.3" }
chrono = { workspace = true }
idna = "0.5"
indexmap = { version = "2", features = ["serde"] }
lazy_static = "1.4.0"
phonenumber = "0.3.2"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unic-ucd-common = { version = "0.9" }
url = { workspace = true }
modify_derive = { path = "../modify_derive" }
