// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryActive } from "./QueryActive";

export type Query = {
  skip?: number;
  limit?: number;
  account_id?: string;
  active?: QueryActive;
};
