// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsItem } from "../../../../stream-connection-stats/StatsItem";

export type Output = { stats: StatsItem };
