[package]
name = "media-sessions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burst = { version = "0.1.0", path = "../burst" }
bytes = "1.3.0"
constants = { version = "0.1.0", path = "../../config/constants" }
db = { version = "0.1.0", path = "../db" }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
futures-util = "0.3.25"
log = "0.4.17"
mongodb = "2.3.1"
parking_lot = "0.12.1"
shutdown = { version = "0.1.0", path = "../shutdown" }
stream-util = { version = "0.1.0", path = "../stream-util" }
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
