// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimezoneDateTime } from "../TimezoneDateTime.js";

export type AnalyticsQueryKind = { now: { offset_date: TimezoneDateTime } } | {
  time_range: { since: TimezoneDateTime; until: TimezoneDateTime };
};
