// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppKindVersion = {
  kind: string | null | undefined;
  version: number | null | undefined;
};
