[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
source = { path = "../../packages/source" }
source-hyper = { path = "../../packages/source-hyper" }
stream = { path = "../../packages/stream" }
logger = { path = "../../packages/logger" }
log = "0.4.17"
proctitle = "0.1.1"
libuv = "2.5.0"
