[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
source = { path = "../../packages/source" }
sender = { path = "../../packages/sender" }
stream = { version = "0.1.0", path = "../../packages/stream" }
