// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicErrorCode =
  | "RESOURCE_NOT_FOUND"
  | "TOO_MANY_REQUESTS"
  | "INTERNAL_DB"
  | "TOKEN_MISSING"
  | "TOKEN_MALFORMED"
  | "TOKEN_NOT_FOUND"
  | "TOKEN_USER_NOT_FOUND"
  | "TOKEN_ACCOUNT_NOT_FOUND"
  | "TOKEN_ADMIN_NOT_FOUND"
  | "TOKEN_OUT_OF_SCOPE"
  | "ACCOUNT_NOT_FOUND"
  | "USER_NOT_FOUND"
  | "AUDIO_FILE_NOT_FOUND"
  | "QUERY_STRING_INVALID"
  | "PAYLOAD_IO"
  | "PAYLOAD_JSON"
  | "PAYLOAD_TOO_LARGE"
  | "PAYLOAD_INVALID"
  | "AUTH_FAILED"
  | "USER_EMAIL_EXISTS";
