// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicError } from "./PublicError";

export interface PublicErrorPayload {
  error: PublicError;
}
