// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicPaymentMethod } from "../../../PublicPaymentMethod";

export type Output = { payment_method: PublicPaymentMethod };
