// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicInvitation } from "../../PublicInvitation";

export type Output = { invitation: PublicInvitation };
