// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Analytics } from "../../../app-analytics/Analytics";

export type Output = { analytics: Analytics };
