// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsQueryKind } from "../../../app-analytics/AnalyticsQueryKind.js";
import type { CountryCodeOrZZ } from "./CountryCodeOrZZ.js";

export type Query = {
  kind: AnalyticsQueryKind;
  stations: string[] | undefined;
  app_kind: string | null | undefined;
  app_version: string | null | undefined;
  country_code: CountryCodeOrZZ | null | undefined;
  min_duration_ms?: number;
};
