// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationQs } from "../../../../../qs/PaginationQs.js";

export type Query = {} & PaginationQs;
