// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "../../../Device";
import type { Paged } from "../../../Paged";

export type Output = Paged<Device>;
