[package]
name = "ffstress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg = { version = "0.1.0", path = "../../packages/ffmpeg" }
tokio = { version = "1.29.0", features = ["full"] }
