// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paged } from "../../../Paged.js";
import type { PublicAccount } from "../../../PublicAccount.js";

export type Output = Paged<PublicAccount>;
