[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
async-trait = "0.1.57"
bytes = "1.3.0"
chrono = "0.4.23"
const-str = "0.5.4"
constants = { version = "0.1.0", path = "../../config/constants" }
cookie = { version = "0.16.2", features = ["sha2", "secure", "signed", "base64"] }
crypt = { version = "0.1.0", path = "../crypt" }
css-inline = "0.8.5"
db = { version = "0.1.0", path = "../db" }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
futures = "0.3.25"
futures-util = "0.3.25"
geoip = { version = "0.1.0", path = "../geoip" }
hex = "0.4.3"
http = { version = "0.1.0", path = "../http" }
http-range = "0.1.5"
hyper = { version = "0.14.27", features = ["full"] }
lazy-regex = "2.5.0"
log = "0.4.17"
mailer = { version = "0.1.0", path = "../mailer" }
media-sessions = { version = "0.1.0", path = "../media-sessions" }
mongodb = "2.4.0"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
parking_lot = "0.12.1"
payments = { version = "0.1.0", path = "../payments" }
prex = { version = "0.1.0", path = "../prex" }
rand = "0.8.5"
random-string = "1.0.0"
serde = "1.0.145"
serde-util = { version = "0.1.0", path = "../serde-util" }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_qs = "0.12.0"
sha1 = "0.10.5"
shutdown = { version = "0.1.0", path = "../shutdown" }
slugify = "0.1.0"
socket2 = "0.4.7"
static_init = "1.0.3"
thiserror = "1.0.38"
time = "0.3.17"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = "0.1.11"
ts-rs = { version = "6.2.0", features = ["chrono", "chrono-impl", "format"] }
upload = { version = "0.1.0", path = "../upload" }
url = "2.3.1"
user-agent = { version = "0.1.0", path = "../user-agent" }
validate = { version = "0.1.0", path = "../validate" }
validify = "0.1.0"

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
config = { version = "0.1.0", path = "../config" }
