[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
const-str = "0.5.4"
constants = { version = "0.1.0", path = "../../config/constants" }
cookie = { version = "0.16.2", features = ["sha2", "secure", "signed", "base64"] }
crypt = { version = "0.1.0", path = "../crypt" }
css-inline = "0.8.5"
db = { version = "0.1.0", path = "../db" }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
futures = { workspace = true }
futures-util = { workspace = true }
geoip = { version = "0.1.0", path = "../geoip" }
hex = "0.4.3"
http = { version = "0.1.0", path = "../http" }
http-range = "0.1.5"
hyper = { workspace = true }
lang = { version = "0.1.0", path = "../lang" }
lazy-regex = { workspace = true }
log = { workspace = true }
macros = { version = "0.1.0", path = "../macros" }
mailer = { version = "0.1.0", path = "../mailer" }
media = { version = "0.1.0", path = "../media" }
mongodb = { workspace = true }
openapi = { version = "0.1.0", path = "../openapi" }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
parking_lot = { workspace = true }
paste = "1.0.14"
payments = { version = "0.1.0", path = "../payments" }
prex = { version = "0.1.0", path = "../prex" }
rand = { workspace = true }
random-string = { workspace = true }
schemars = { workspace = true, features = ["preserve_order"] }
serde = { workspace = true }
serde-util = { version = "0.1.0", path = "../serde-util" }
serde_json = { workspace = true }
serde_qs = "0.12.0"
serde_with = "3.0.0"
sha1 = "0.10.5"
shutdown = { version = "0.1.0", path = "../shutdown" }
slugify = "0.1.0"
socket2 = "0.4.7"
static_init = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
ts-rs = { workspace = true, features = ["chrono", "chrono-impl", "format", "indexmap-impl"] }
upload = { version = "0.1.0", path = "../upload" }
url = { workspace = true }
user-agent = { version = "0.1.0", path = "../user-agent" }
validate = { version = "0.1.0", path = "../validate" }
modify = { path = "../modify" }
validator = { workspace = true }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
config = { version = "0.1.0", path = "../config" }
