[package]
name = "prex"
version = "0.1.0"
edition = "2021"

[dependencies]
# ip2country = "0.2.0"
tokio = { version = "1.29.0", features = ["full"] }
tower = { version = "0.4.8", features = ["full"] }
hyper = { version = "0.14.27", features = ["full"] }
futures = "0.3"
async-trait = "0.1.51"
regex = "1.5.4"
thiserror = "1.0.26"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
http-auth-basic = "0.3.3"
ip_rfc = "0.1.0"
bytes = "1.4.0"
log = "0.4.17"
serde_qs = "0.12.0"
constants = { version = "0.1.0", path = "../../config/constants" }
hyper-tungstenite = "0.13.0"
tokio-tungstenite = "0.21.0"
tungstenite = "0.21.0"
pin-project-lite = "0.2.13"
hyper-util = "0.1.2"
modify = { path = "../modify" }
validator = { version = "0.16.1", features = ["derive", "phone", "unic"] }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
