[package]
name = "prex"
version = "0.1.0"
edition = "2021"

[dependencies]
# ip2country = "0.2.0"
tokio = { workspace = true }
tower = { version = "0.4.8", features = ["full"] }
hyper = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
http-auth-basic = "0.3.3"
ip_rfc = "0.1.0"
bytes = { workspace = true }
log = { workspace = true }
serde_qs = "0.12.0"
constants = { version = "0.1.0", path = "../../config/constants" }
hyper-tungstenite = "0.13.0"
tokio-tungstenite = "0.21.0"
tungstenite = "0.21.0"
pin-project-lite = "0.2.13"
hyper-util = "0.1.2"
modify = { path = "../modify" }
validator = { workspace = true }

[dev-dependencies]
test-util = { version = "0.1.0", path = "../test-util" }
