// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Output {
  listeners_last_24h: number;
  listeners_last_7d: number;
  listeners_last_30d: number;
}
