// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Output {
  sessions_24h: number;
  sessions_7d: number;
  sessions_30d: number;
  listeners_24h: number;
  listeners_7d: number;
  listeners_30d: number;
}
