// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Output = {
  id: string;
  name: string;
  slogan: string | null | undefined;
  picture_id: string;
  now_playing: string | null | undefined;
  transmission_error: string | null | undefined;
};
