[build]
rustflags = ["--cfg", "tokio_unstable"]
# target="x86_64-unknown-linux-musl"
# limit on parallel jobs to prevent os crash
jobs = 12

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
