// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Query = {
  customer_id: string;
  payment_method_nonce: string;
  device_data?: string;
};
