// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Response {
  card_type: string;
  expiration_month: string | null;
  expiration_year: string | null;
  last_4: string;
  payment_method_token: string;
}
