[package]
name = "ffmpeg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
constants = { version = "0.1.0", path = "../../config/constants" }
log = { workspace = true }
pin-project = { workspace = true }
serde_json = { workspace = true }
spsc = { version = "0.1.0", path = "../spsc" }
stream-util = { version = "0.1.0", path = "../stream-util" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
url = { workspace = true }

[dev-dependencies]
async-stream = { workspace = true }
