// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../../../CountryCode";
import type { ZZ } from "./ZZ";

export type CountryCodeOrZZ = ZZ | CountryCode;
