// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCodeOrZZ } from "./CountryCodeOrZZ";

export type Query = {
  since: /** time::DateTime */ string;
  until: /** time::DateTime */ string;
  stations: string[] | undefined;
  browser: string | null;
  os: string | null;
  domain: string | null;
  country_code: CountryCodeOrZZ | null;
};
