// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paged } from "../../../Paged";
import type { Plan } from "../../../db/Plan";

export type Output = Paged<Plan>;
