[package]
name = "metre"
version = "0.1.0"
edition = "2021"

[dependencies]
metre-macros = { version = "0.1.0", path = "../metre-macros" }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
json_comments = "0.2.1"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
toml = "0.7.6"
serde_yaml = "0.9.25"
thiserror = "1.0.44"
reqwest = { version = "0.11.18", features = ["blocking"] }
