// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsByBrowser } from "./AnalyticsByBrowser";
import type { AnalyticsByCountry } from "./AnalyticsByCountry";
import type { AnalyticsByDay } from "./AnalyticsByDay";
import type { AnalyticsByMonth } from "./AnalyticsByMonth";
import type { AnalyticsByOs } from "./AnalyticsByOs";
import type { AnalyticsByStation } from "./AnalyticsByStation";
import type { AnalyticsDate } from "./AnalyticsDate";
import type { AnalyticsStation } from "./AnalyticsStation";

export type Analytics = {
  stations: Array<AnalyticsStation>;
  start_date: AnalyticsDate;
  end_date: AnalyticsDate;
  sessions: number;
  ips: number;
  total_duration_ms: number;
  by_day: Array<AnalyticsByDay>;
  by_month: Array<AnalyticsByMonth>;
  by_browser: Array<AnalyticsByBrowser>;
  by_os: Array<AnalyticsByOs>;
  by_country: Array<AnalyticsByCountry>;
  by_station: Array<AnalyticsByStation>;
};
