// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../CountryCode";

export type AnalyticsByCountry = {
  country_code: CountryCode | null;
  sessions: number;
  total_duration_ms: number;
};
