// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsQueryKind = {
  now: { offset_date: /** time::DateTime */ string };
} | {
  time_range: {
    since: /** time::DateTime */ string;
    until: /** time::DateTime */ string;
  };
};
