// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsItem<K> = {
  key: K;
  sessions: number;
  total_duration_ms: number;
  total_transfer_bytes: number;
};
