// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsByBrowser = {
  browser: string | null;
  sessions: number;
  total_duration_ms: number;
};
