// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsByDay = {
  year: number;
  month: number;
  day: number;
  sessions: number;
  total_duration_ms: number;
};
