[package]
name = "prex"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
tower = { version = "0.4.8", features = ["full"] }
hyper = { version = "0.14.11", features = ["full"] }
futures = "0.3"
async-trait = "0.1.51"
regex = "1.5.4"
thiserror = "1.0.26"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
http-auth-basic = "0.3.3"
ip_rfc = "0.1.0"
bytes = "1.4.0"
log = "0.4.17"
test-util = { version = "0.1.0", path = "../test-util" }
