[package]
name = "validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email_address = "0.2.4"
lazy-regex = "2.3.1"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.40"
url = "2.3.1"
