[package]
name = "validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
regex_static = "0.1.1"
# serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.40"
# url = "2.3.1"
