// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Payload = {
  title?: string | null | undefined;
  artist?: string | null | undefined;
  album?: string | null | undefined;
  album_artist?: string | null | undefined;
  genre?: string | null | undefined;
  year?: number | null | undefined;
  comment?: string | null | undefined;
  track?: number | null | undefined;
};
