[package]
name = "openstream"
version = "0.1.0"
edition = "2021"

[features]
tracing = [ "tokio/tracing" ]

[dependencies]
# source = { path = "../../packages/source" }
# channels = { version = "0.1.0", path = "../../packages/channels" }
# ip = { version = "0.1.0", path = "../../packages/ip" }
# router = { version = "0.1.0", path = "../../packages/router" }
# rust_ipify = "1.1.0"
tokio = { workspace = true }
source-alt = { path = "../../packages/source-alt" }
stream = { path = "../../packages/stream" }
logger = { path = "../../packages/logger" }
log = { workspace = true }
dotenv = "0.15.0"
owo-colors = { version = "3.5.0", path = "../../packages/owo-colors" }
config = { version = "0.1.0", path = "../../packages/config" }
db = { version = "0.1.0", path = "../../packages/db" }
mongodb = { workspace = true }
drop-tracer = { version = "0.1.0", path = "../../packages/drop-tracer" }
shutdown = { version = "0.1.0", path = "../../packages/shutdown" }
which = "4.3.0"
clap = { version = "4.0.26", features = ["derive"] }
futures = { workspace = true }
api = { version = "0.1.0", path = "../../packages/api" }
chrono = { workspace = true }
dialoguer = "0.10.2"
defer-lite = "1.0.0"
anyhow = "1.0.66"
serde-util = { version = "0.1.0", path = "../../packages/serde-util" }
jemallocator = "0.5.0"
uid = { version = "0.1.0", path = "../../packages/uid" }
local-ip-address = "0.5.0"
crypt = { version = "0.1.0", path = "../../packages/crypt" }
thiserror = { workspace = true }
hyper = { workspace = true }
validate = { version = "0.1.0", path = "../../packages/validate" }
mailer = { version = "0.1.0", path = "../../packages/mailer" }
payments = { version = "0.1.0", path = "../../packages/payments" }
assets = { version = "0.1.0", path = "../../packages/assets" }
console-subscriber = { version = "0.1.9", features = ["parking_lot"] }
media = { version = "0.1.0", path = "../../packages/media" }