export const google_play_langs = {
  "af": "Afrikáans",
  "sq": "Albanés",
  "de-DE": "Alemán",
  "am": "Amárico",
  "ar": "Árabe",
  "hy-AM": "Armenio",
  "az-AZ": "Azerbaiyano",
  "bn-BD": "Bengalí",
  "be": "Bielorruso",
  "my-MM": "Birmano",
  "bg": "Búlgaro",
  "kn-IN": "Canarés",
  "ca": "Catalán",
  "cs-CZ": "Checo",
  "zh-HK": "Chino (Hong Kong)",
  "zh-CN": "Chino (simplificado)",
  "zh-TW": "Chino (tradicional)",
  "si-LK": "Cingalés",
  "ko-KR": "Coreano",
  "hr": "Croata",
  "da-DK": "Danés",
  "sk": "Eslovaco",
  "sl": "Esloveno",
  "es-ES": "Español (España)",
  "es-US": "Español (Estados Unidos)",
  "es-419": "Español (Latinoamérica)",
  "et": "Estonio",
  "fil": "Filipino",
  "fi-FI": "Finés",
  "fr-CA": "Francés (Canadá)",
  "fr-FR": "Francés (Francia)",
  "gl-ES": "Gallego",
  "ka-GE": "Georgiano",
  "el-GR": "Griego",
  "gu": "Gujarati",
  "iw-IL": "Hebreo",
  "hi-IN": "Hindi",
  "hu-HU": "Húngaro",
  "id": "Indonesio",
  "en-IN": "Inglés",
  "en-SG": "Inglés",
  "en-ZA": "Inglés",
  "en-AU": "Inglés (Australia)",
  "en-CA": "Inglés (Canadá)",
  "en-US": "Inglés (Estados Unidos)",
  "en-GB": "Inglés (Reino Unido)",
  "is-IS": "Islandés",
  "it-IT": "Italiano",
  "ja-JP": "Japonés",
  "km-KH": "Jemer",
  "kk": "Kazajo",
  "ky-KG": "Kirguís",
  "lo-LA": "Laosiano",
  "lv": "Letón",
  "lt": "Lituano",
  "mk-MK": "Macedonio",
  "ml-IN": "Malabar",
  "ms": "Malayo",
  "ms-MY": "Malayo (Malasia)",
  "mr-IN": "Maratí",
  "mn-MN": "Mongol",
  "nl-NL": "Neerlandés",
  "ne-NP": "Nepalí",
  "no-NO": "Noruego",
  "pa": "Panyabí",
  "fa": "Persa",
  "fa-AE": "Persa",
  "fa-AF": "Persa",
  "fa-IR": "Persa",
  "pl-PL": "Polaco",
  "pt-BR": "Portugués (Brasil)",
  "pt-PT": "Portugués (Portugal)",
  "rm": "Retorrománico",
  "ro": "Rumano",
  "ru-RU": "Ruso",
  "sr": "Serbio",
  "sv-SE": "Sueco",
  "sw": "Swahili",
  "th": "Tailandés",
  "ta-IN": "Tamil",
  "te-IN": "Telugu",
  "tr-TR": "Turco",
  "uk": "Ucraniano",
  "ur": "Urdu",
  "eu-ES": "Vasco",
  "vi": "Vietnamita",
  "zu": "Zulú"
}

export type GooglePlayLang = keyof typeof google_play_langs;

export const is_lang = (lang: string): lang is GooglePlayLang => {
  return Object.hasOwn(google_play_langs, lang)
}