[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# env_logger = "0.9.1"
# pretty_env_logger = "0.4.0"
# sensible-env-logger = { version = "0.3.1", features = ["chrono", "local-time"] }
chrono = { workspace = true }
crossterm = "0.25.0"
env_logger = { version = "0.10.0", path = "../env_logger" }
log = { workspace = true }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
static_init = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "parsing", "serde", "serde-well-known", "serde-human-readable"] }
