// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKey } from "../../../ApiKey";

export type Output = { api_key: ApiKey; token: string; media_key: string };
