// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Payload {
  price?: number;
  identifier?: string;
  slug?: string;
  display_name?: string;
  color?: string;
  stations?: number;
  listeners?: number;
  transfer?: number;
  storage?: number;
  is_user_selectable?: boolean;
}
