// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKey } from "../../../ApiKey.js";
import type { Paged } from "../../../../Paged.js";

export type Output = Paged<ApiKey>;
