// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserPublicUser } from "../../../../../db/UserPublicUser";

export interface Output {
  user: UserPublicUser;
  token: string;
  media_key: string;
}
