[package]
name = "db"
version = "0.1.0"
edition = "2021"

[features]
default = ["analytics-max-concurrent"]
# default = []
analytics-max-concurrent = []

# do not enable this, is for internal benchmarking only
test-analytics-base-measure = []


[dependencies]
lazy_static = "1.4.0"
mongodb = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true, features = [ "serde" ] }
serde-util = { path = "../serde-util" }
uid = { path = "../uid" }
once_cell = { workspace = true, features = ["parking_lot"] }
bytes = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
futures-util = { workspace = true }
woothee = { version = "0.13.0", features = ["serde", "serde_derive"] }
user-agent = { version = "0.1.0", path = "../user-agent" }
validate = { version = "0.1.0", path = "../validate" }
async-stream = { workspace = true }
ts-rs = { workspace = true, features = ["chrono", "chrono-impl", "format", "indexmap-impl"] }
time = { workspace = true, features = ["serde-well-known", "local-offset", "serde-human-readable"] }
indexmap = { version = "1.9.2", features = ["serde"] }
hyper = { workspace = true }
prex = { version = "0.1.0", path = "../prex" }
crypt = { version = "0.1.0", path = "../crypt" }
thiserror = { workspace = true }
macros = { version = "0.1.0", path = "../macros" }
const-str = { version = "0.5.3", features = ["all"] }
rand = { workspace = true }
static_init = { workspace = true }
parking_lot = { workspace = true }
modify = { path = "../modify" }
validator = { workspace = true }
ril = { version = "0.9.0", features = ["all"] }
lazy-regex = { workspace = true }
geoip = { version = "0.1.0", path = "../geoip" }
rayon = "1.7.0"
deepsize = { workspace = true }
human_bytes = { version = "0.4.1", default-features = false }
strum = "0.24.1"
arr_macro = "0.2.1"
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
derive_more = "0.99.17"
random-string = { workspace = true }
url = { workspace = true }
constants = { version = "0.1.0", path = "../../config/constants" }
paste = "1.0.12"
image = { version = "0.24.6", features = ["webp-encoder", "webp", "rgb", "mp4parse"] }
lang = { version = "0.1.0", path = "../lang" }
ffmpeg = { version = "0.1.0", path = "../ffmpeg" }
schemars = { workspace = true }
serde_json = { workspace = true }
compact_str = { workspace = true }
openapi = { version = "0.1.0", path = "../openapi" }

[dev-dependencies]
serde_json = { workspace = true }
logger = { version = "0.1.0", path = "../logger" }
