[package]
name = "stream-alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# channels = { path = "../channels" }
bytes = "1.2.1"
hyper = { version = "0.14.27", features = ["full"] }
prex = { version = "0.1.0", path = "../prex" }
tokio = { version = "1.29.0", features = ["full"] }
log = "0.4.17"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
async-trait = "0.1.58"
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
shutdown = { version = "0.1.0", path = "../shutdown" }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = "1.0.147"
futures = "0.3.25"
http = { version = "0.1.0", path = "../http" }
db = { version = "0.1.0", path = "../db" }
serde-util = { version = "0.1.0", path = "../serde-util" }
mongodb = "2.7.0"
parking_lot = "0.12.1"
constants = { version = "0.1.0", path = "../../config/constants" }
thiserror = "1.0.38"
socket2 = "0.4.7"
ip-counter = { version = "0.1.0", path = "../ip-counter" }
ip_rfc = "0.1.0"
defer = "0.1.0"
url = "2.3.1"
rand = "0.8.5"
media = { version = "0.1.0", path = "../media" }
mp3 = { version = "0.3.4", path = "../mp3" }
proxy-protocol = { version = "0.1.0", path = "../proxy-protocol" }

[features]

