# openstream api options
[openstream]

# string - URL (required)
# openstream api base URL
# env.OPENSTREAM_FRONT_OPENSTREAM_API_BASE_URL
api_base_url="http://127.0.0.1:10700"


[session]
# string (required)
# changes to this secret will invalidate sessions
# env.OPENSTREAM_FRONT_SESSION_SECRET
secret = "supersecret"

# number (required)
# sessions will expire after specified days from the last user request
# env.OPENSTREAM_FRONT_SESSION_MAX_AGE_DAYS
max_age_days = 7

# string (required)
# name of the session cookie
# env.OPENSTREAM_FRONT_SESSION_COOKIE_NAME
cookie_name = "openstream-front-tid"


# studio configuration (optional), if not provided no studio interface will be created
[studio]
# boolean (required)
# enable app web interface or not
# env.OPENSTREAM_FRONT_STUDIO_ENABLED
enabled=true

# number (required)
# port to bind the admin interface to
# env.OPENSTREAM_FRONT_STUDIO_PORT
port = 18965

# admin configuration (optional), if not provided no admin interface will be created
[admin]
# boolean (required)
# enable app web interface or not
# env.OPENSTREAM_FRONT_ADMIN_ENABLED
enabled=true

# number (required)
# port to bind the admin interface to
# env.OPENSTREAM_FRONT_ADMIN_PORT
port = 18865

[embed]
# boolean (required)
# enable app web interface or not
# env.OPENSTREAM_FRONT_EMBED_ENABLED
enabled=true

# number (required)
# port to bind the admin interface to
# env.OPENSTREAM_FRONT_EMBED_PORT
port = 18765

# payments configuration (optional), if not provided no payments interface will be created
[payments]
# boolean (required)
# enable app web interface or not
# env.OPENSTREAM_FRONT_PAYMENTS_ENABLED
enabled=false

# number (required)
# port to bind the admin interface to
# env.OPENSTREAM_FRONT_PAYMENTS_PORT
port = 17100

# string (required)
# x-access-token header will be checked in each request, and it must match this value
# env.OPENSTREAM_FRONT_PAYMENTS_ACCESS_TOKEN
access_token = ""

# braintree credentials (required)
[payments.credentials]
# braintree environment (required) can be "sandbox" or "production"
# env.OPENSTREAM_FRONT_PAYMENTS_ENVIRONMENT
environment = "sandbox"

# braintree merchant id (required)
# env.OPENSTREAM_FRONT_PAYMENTS_MERCHANT_ID
merchant_id = ""

# braintree public key (required)
# env.OPENSTREAM_FRONT_PAYMENTS_CREDENTIALS_PUBLIC_KEY 
public_key = ""

# braintree private key (required)
# env.OPENSTREAM_FRONT_PAYMENTS_CREDENTIALS_PRIVATE_KEY 
private_key = ""



# hostnames configuration 
[hosts.default]
cookie_domain = "openstream.fm"
site = { host = "openstream.fm" }
studio = { host = "studio.openstream.fm" }
admin = { host = "admin.openstream.fm" }
api = { host = "api.openstream.fm" }
storage = { host = "storage.openstream.fm" }
stream = { host = "stream.openstream.fm" }
source = { host = "source.openstream.fm", port = 8000 }