[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
mongodb = { version = "2.3.0", features = [ "bson-chrono-0_4" ] }
serde = "1.0.145"
tokio = { version = "1.21.2", features = [ "full" ] }
chrono = { version = "0.4.22", features = [ "serde" ] }
serde-util = { path = "../serde-util" }
uid = { path = "../uid" }
once_cell = { version = "1.15.0", features = ["parking_lot"] }
bytes = "1.2.1"
async-trait = "0.1.58"
syn = "1.0.103"
quote = "1.0.21"
log = "0.4.17"
futures-util = "0.3.25"
unused = "0.1.0"
woothee = { version = "0.13.0", features = ["serde", "serde_derive"] }
user-agent = { version = "0.1.0", path = "../user-agent" }

[dev-dependencies]
serde_json = "1.0.86"
