[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive", "rc"] }
toml = { version = "0.5.9", features = ["indexmap", "preserve_order"] }
url = { version = "2.3.1", features = ["serde"] }
