[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
constants = { version = "0.1.0", path = "../../config/constants" }
log = { workspace = true }
parking_lot = { workspace = true }
static_init = { workspace = true }
tokio = { workspace = true }
burst = { version = "0.1.0", path = "../burst" }
