[package]
name = "channels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
constants = { version = "0.1.0", path = "../../config/constants" }
log = "0.4.17"
parking_lot = "0.12.1"
static_init = "1.0.3"
tokio = { version = "1.29.0", features = ["full"] }
burst = { version = "0.1.0", path = "../burst" }
