// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTime } from "../DateTime.js";

export type ApiKey = {
  _id: string;
  is_current: boolean;
  title: string;
  user_id: string | null | undefined;
  admin_id: string | null | undefined;
  created_at: DateTime;
  last_used_at: DateTime | null | undefined;
};
