// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicAdmin } from "../PublicAdmin.js";
import type { PublicUser } from "../db/PublicUser.js";

export type Me =
  | { scope: "global" }
  | ({ scope: "admin" } & { admin: PublicAdmin })
  | ({ scope: "user" } & { user: PublicUser });
