// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountInvitationState } from "../db/AccountInvitationState.js";
import type { DateTime } from "../DateTime.js";
import type { InvitationAccount } from "./InvitationAccount.js";
import type { InvitationAdminSender } from "./InvitationAdminSender.js";
import type { InvitationReceiver } from "./InvitationReceiver.js";
import type { InvitationUserSender } from "./InvitationUserSender.js";

export type PublicInvitation = {
  id: string;
  user_sender_id: string | null;
  admin_sender_id: string | null;
  account_id: string;
  receiver_email: string;
  created_at: DateTime;
  deleted_at: DateTime | null;
  is_expired: boolean;
  expires_at: DateTime;
  account: InvitationAccount | null;
  user_sender: InvitationUserSender | null;
  admin_sender: InvitationAdminSender | null;
  receiver: InvitationReceiver | null;
} & AccountInvitationState;
