// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationPicture } from "../../../db/StationPicture.js";

export type Output = StationPicture;
