[package]
name = "source-alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ffmpeg = { path = "../ffmpeg" }
# channels = { path = "../channels" }
bytes = { workspace = true }
static_init = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
hyper = { workspace = true }
prex = { path = "../prex" }
stream-util = { path = "../stream-util" }
tokio-stream = { workspace = true }
regex_static = { workspace = true }
constants = { version = "0.1.0", path = "../../config/constants" }
log = { workspace = true }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
once_cell = { workspace = true }
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
shutdown = { version = "0.1.0", path = "../shutdown" }
http-basic-auth = "0.1.2"
db = { version = "0.1.0", path = "../db" }
user-agent = { version = "0.1.0", path = "../user-agent" }
proxy-protocol = { version = "0.1.0", path = "../proxy-protocol" }
geoip = { version = "0.1.0", path = "../geoip" }
rand = { workspace = true }
socket2 = "0.5.2"
thiserror = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true }
lazy-regex = { workspace = true }
serde-util = { version = "0.1.0", path = "../serde-util" }
serde_qs = "0.12.0"
media = { version = "0.1.0", path = "../media" }

[features]
