[package]
name = "source-alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
static_init = "1.0.3"
tokio = { version = "1.27.0", features = ["full"] }
ffmpeg = { path = "../ffmpeg" }
parking_lot = "0.12.1"
hyper = { version = "0.14.20", features = ["full"] }
prex = { path = "../prex" }
stream-util = { path = "../stream-util" }
tokio-stream = "0.1.10"
regex_static = "0.1.1"
channels = { path = "../channels" }
constants = { version = "0.1.0", path = "../../config/constants" }
log = "0.4.17"
owo-colors = { version = "3.5.0", path = "../owo-colors" }
once_cell = "1.15.0"
drop-tracer = { version = "0.1.0", path = "../drop-tracer" }
media-sessions = { version = "0.1.0", path = "../media-sessions" }
shutdown = { version = "0.1.0", path = "../shutdown" }
http-basic-auth = "0.1.2"
db = { version = "0.1.0", path = "../db" }
user-agent = { version = "0.1.0", path = "../user-agent" }
proxy-protocol = { version = "0.1.0", path = "../proxy-protocol" }
geoip = { version = "0.1.0", path = "../geoip" }
rand = "0.8.5"

[features]
