// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryCode } from "../../CountryCode.js";
import type { Headers } from "./Headers.js";
import type { Method } from "./Method.js";
import type { SocketAddr } from "./SocketAddr.js";
import type { Uri } from "./Uri.js";
import type { UserAgent } from "../../UserAgent.js";
import type { Version } from "./Version.js";

export type Request = {
  real_ip: string;
  country_code: CountryCode | null | undefined;
  local_addr: SocketAddr;
  remote_addr: SocketAddr;
  version: Version;
  method: Method;
  uri: Uri;
  headers: Headers;
  user_agent: UserAgent;
};
