// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Uri {
  uri: string;
  scheme: string | null;
  host: string | null;
  port: number | null;
  path: string;
  query: string | null;
}
