// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Uri = {
  uri: string;
  scheme: string | null | undefined;
  host: string | null | undefined;
  port: number | null | undefined;
  path: string;
  query: string | null | undefined;
};
