[package]
name = "test-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
proc-macro2 = "1.0.7"
quota = "0.0.0"
quote = "1"
syn = { version = "1.0.56", features = ["full"] }
tokio = { version = "1.27.0", features = ["full"] }
