// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../db/Metadata";

export interface AccountPatch {
  name?: string;
  userMetadata?: Metadata;
  systemMetadata?: Metadata;
}
