// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../db/Metadata";

export interface AdminPatch {
  first_name?: string;
  last_name?: string;
  system_metadata?: Metadata;
}
