// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../db/Metadata.js";

export type AdminPatch = {
  first_name?: string;
  last_name?: string;
  language?: string | null;
  system_metadata?: Metadata;
};
