// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../db/Metadata";
import type { StationPatchLimits } from "./StationPatchLimits";

export interface StationPatch {
  name?: string;
  limits?: StationPatchLimits;
  user_metadata?: Metadata;
  system_metadata?: Metadata;
}
