// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../db/Metadata";
import type { StationFrequency } from "../StationFrequency";
import type { StationPatchLimits } from "./StationPatchLimits";

export interface StationPatch {
  name?: string;
  slogan: string | null | null;
  description: string | null | null;
  frequencies?: Array<StationFrequency>;
  email: string | null | null;
  phone: string | null | null;
  whatsapp: string | null | null;
  website_url: string | null | null;
  twitter_url: string | null | null;
  facebook_url: string | null | null;
  instagram_url: string | null | null;
  youtube_url: string | null | null;
  twitch_url: string | null | null;
  google_play_url: string | null | null;
  app_store_url: string | null | null;
  limits?: StationPatchLimits;
  user_metadata?: Metadata;
  system_metadata?: Metadata;
}
