// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../db/Metadata";
import type { PayloadLimits } from "./PayloadLimits";
import type { StationFrequency } from "../../../StationFrequency";

export interface Payload {
  account_id: string;
  picture_id: string;
  name: string;
  slogan: string | null;
  description: string | null;
  email: string | null;
  phone: string | null;
  whatsapp: string | null;
  website_url: string | null;
  twitter_url: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  youtube_url: string | null;
  twitch_url: string | null;
  google_play_url: string | null;
  app_store_url: string | null;
  frequencies: Array<StationFrequency> | null;
  limits?: PayloadLimits;
  user_metadata?: Metadata;
  system_metadata?: Metadata;
}
