// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "../../../db/Metadata";
import type { PayloadLimits } from "./PayloadLimits";

export interface Payload {
  name: string;
  owner_id: string | null;
  limits?: PayloadLimits;
  user_metadata?: Metadata;
  system_metadata?: Metadata;
}
