[package]
name = "spsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.28"
parking_lot = "0.12.1"
pin-project = "1.0.12"

[dev-dependencies]
async-stream = "0.3.3"
tokio = { version = "1.27.0", features = ["full"] }
test-util = { version = "0.1.0", path = "../test-util" }
tokio-stream = "0.1.11"
log = "0.4.17"