[package]
name = "spsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = { workspace = true }
parking_lot = { workspace = true }
pin-project = { workspace = true }

[dev-dependencies]
async-stream = { workspace = true }
tokio = { workspace = true }
test-util = { version = "0.1.0", path = "../test-util" }
tokio-stream = { workspace = true }
log = { workspace = true }