[package]
name = "geoip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# static_init = { workspace = true }
deepsize = { workspace = true }
ip2geo = "0.1.0"
log = { workspace = true }
macros = { version = "0.1.0", path = "../macros" }
schemars = { workspace = true }
serde = { workspace = true }
strum = { version = "0.24.1", features = ["phf", "derive", "strum_macros"] }
ts-rs = { workspace = true }
