[package]
name = "geoip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# static_init = "1.0.3"
deepsize = "0.2.0"
ip2geo = "0.1.0"
log = "0.4.17"
macros = { version = "0.1.0", path = "../macros" }
serde = { version = "1.0.160", features = ["derive"] }
strum = { version = "0.24.1", features = ["phf", "derive", "strum_macros"] }
ts-rs = "6.2.0"
