// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Payload = {
  identifier: string;
  slug: string;
  display_name: string;
  is_user_selectable: boolean;
  price: number;
  color: string;
  stations: number;
  listeners: number;
  transfer: number;
  storage: number;
};
