// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Output = {
  kind: "found";
  user_id: string;
  user_first_name: string;
  user_last_name: string;
  user_email: string;
  already_used: boolean;
  expired: boolean;
} | { kind: "not_found" };
