[package]
name = "assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
rust-embed = { version = "6.7.0", features = ["debug-embed"] }
base64-compat = "1.0.0"
mime_guess = "2.0.4"
rust-embed-for-web = "11.1.1"
socket2 = "0.5.3"
http = { version = "0.1.0", path = "../http" }
owo-colors = { version = "3.5.0", path = "../owo-colors" }
prex = { version = "0.1.0", path = "../prex" }
shutdown = { version = "0.1.0", path = "../shutdown" }
