name: backend-integration-tests

on: 
  push:
    paths:
      - "rs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "openstream.sample.toml"
      - "openstream.sample.jsonc"
    branches: [ master, dev ]
  
  pull_request:
    paths:
      - "rs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "openstream.sample.toml"
      - "openstream.sample.jsonc"
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:

  # skip_check:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     should_skip: ${{ steps.skip_check.outputs.should_skip }}
  #   steps:
  #     - id: skip_check
  #       uses: fkirc/skip-duplicate-actions@v5

  backend-integration-tests:
    # needs: skip_check
    # if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: self-hosted-integration-tests

    steps:

    - uses: actions/checkout@v3

    # - uses: actions/cache@v3
    #   with:
    #     path: ./target
    #     key: "${{ runner.os }}-cargo-integration-tests-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}"
    #     restore-keys: |
    #       ${{ runner.os }}-cargo-integration-tests-
    
    - name: Local cargo cache
      id: integration-tests-cargo-cache
      uses: MasterworksIO/action-local-cache@1.0.0
      with:
        path: ./target
        key: integration-tests-cargo-target

    - name: Cargo Integration Tests
      run: cargo test --test "*"