# this workflow is only used to create a build cache for the release job
name: backend-build-release

on: 

  workflow_dispatch:

  push:
    paths:
      - "rs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "openstream.sample.toml"
      - "openstream.sample.jsonc"
    branches: [ master ]
  
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"

jobs:

  # skip_check:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     should_skip: ${{ steps.skip_check.outputs.should_skip }}
  #   steps:
  #     - id: skip_check
  #       uses: fkirc/skip-duplicate-actions@v5

  backend-build:
    # needs: skip_check
    # if: needs.skip_check.outputs.should_skip != 'true'

    # runs-on: self-hosted-build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      with:
        path: |
          ./target
          ~/.cargo
        key: ${{ runner.os }}-build-release-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}
        restore-keys: |
          ${{ runner.os }}-build-release-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}
          ${{ runner.os }}-build-release-

    # - name: Local cargo cache
    #   id: build-cargo-cache
    #   uses: MasterworksIO/action-local-cache@1.0.0
    #   with:
    #     path: ./target/
    #     key: build-cargo-target

    # we build in release mode to be able to use the cache from this run within the release job
    - name: Cargo Build
      run: cargo build --release