name: front-server-build

on: 
  push:
    branches: [ master, dev ]
  
  pull_request_target:
      branches: [ master, dev ]

jobs:

  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5

  front-server-build:

    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    defaults:
      run:
        working-directory: ./front/server

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.0
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run ci
        working-directory: ./front
      - run: npm run build --if-present