name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:

    runs-on: self-hosted-release

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      
      - uses: actions/checkout@v3
      # - uses: Swatinem/rust-cache@v2
      #   with:
      #     cache-all-crates: true
      #     shared-key: release

      - name: Local cargo cache
        id: release-cargo-cache
        uses: MasterworksIO/action-local-cache@1.0.0
        with:
          path: ./target/
          key: release-cargo-target

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # cache doesn't seem to work under tag branches, not even to recover from master branch saved cache
      # - uses: actions/cache@v3
      #   with:
      #     path: ./target
      #     key: ${{ runner.os }}-cargo-build-release-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cargo-build-release-
          
      - run: npm ci
        working-directory: ./scripts

      - run: npm run build
        working-directory: ./scripts

      - run: npm run script:release
        working-directory: ./scripts
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            release.tar.gz