name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"

jobs:

  release:

    # runs-on: self-hosted-release
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      
      # - uses: Swatinem/rust-cache@v2
      #   with:
        #     cache-all-crates: true
        #     shared-key: release
        
        # - name: Local cargo cache
        #   id: release-cargo-cache
        #   uses: MasterworksIO/action-local-cache@1.0.0
        #   with:
          #     path: ./target/
          #     key: release-cargo-target
      
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-release
          cache-all-crates: true
          cache-targets: true
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/master' }}

      # - uses: actions/cache@v4
      #   with:
      #     path: |
      #       ./target
      #       ~/.cargo
      #     key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', './rs') }}
      #       ${{ runner.os }}-build-

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: ./scripts

      - run: npm run build
        working-directory: ./scripts

      - run: npm run script:release
        working-directory: ./scripts
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            release.tar.gz