// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Output =
  | { result: "ok" }
  | { result: "not-found" }
  | { result: "expired" }
  | { result: "already-accepted" }
  | { result: "already-rejected" };
